# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75b3ea6115adcfea95a231761d9f859c2eed4bb1a10e63db37a56c44ed1f0cf652bd1ddbbf5369b277992d17c9f5b96aad49a204055ead41801047e4717b7679

test:
  secret_key_base: a3a375868af14053467043fe689e7b522b8132545c93a12684fb9ff0301c474679566144f6c5afebd9cb06ef07224a42bde0cd4786fb45f77a75e3cf266ef721

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
